trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
# Build Stage
- stage: BuildFrontend
  displayName: 'Build Frontend'
  jobs:
  - job: BuildJob
    displayName: 'Install & Build'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'

    - script: npm install
      workingDirectory: 'Product-Catalog/Client'
      displayName: 'Install Frontend Dependencies'

    - script: npm run build
      workingDirectory: 'Client1'
      displayName: 'Build Frontend'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'Client1/build'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/frontend.zip'
        replaceExistingArchive: true
      displayName: 'Archive Frontend Build'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      displayName: 'Publish Artifact'